### ISSUE TITLE
Questions about the “Getting started” section

### ISSUE THREAD

**Issue by tysongach** [salesforce-ux/sass-deprecate#12]
Hello!

Lovely work on this; thanks for open-sourcing! I had a couple questions about the [“Getting started”](https://github.com/salesforce-ux/sass-deprecate#getting-started) section in the readme:

1. Under **v1.1.0** section, should `$app-version: '1.0.0';` be `$app-version: '1.1.0';`?
1. As currently written, it seems to indicate (under the **v2.0.0** section) that deprecations warnings won’t be thrown by the compiler _until_ you ship `2.0.0`. But wouldn’t those warnings start getting thrown in `1.1.0` in this example (since this is when you add the deprecation mixin around `.button`)?
1. Following up on the above and if I’m understanding correctly, in `2.0.0` you as a developer would completely _remove_ `.button` and its styles? So at this point no deprecated code would be shipped (as indicated) and therefore these deprecation warnings also do not get shipped and they would not be output to the compiler in `2.0.0`. Is this correct? Or do you continue to ship the `.button` selector wrapped in the `deprecated` mixin?

Thanks!

**Comment by kaelig** [comment]
Hi @tysongach, thank you for your feedback!

> 1. Under **v1.1.0** section, should `$app-version: '1.0.0';` be `$app-version: '1.1.0';`?

Good catch, thank you! Fixed in e7a60eaaf93e7ed884296a848e287a0dae24d39a

> 2. As currently written, it seems to indicate (under the **v2.0.0** section) that deprecations warnings won’t be thrown by the compiler _until_ you ship `2.0.0`. But wouldn’t those warnings start getting thrown in `1.1.0` in this example (since this is when you add the deprecation mixin around `.button`)?

The idea is that you'd bump the version number to 2.0.0 **before** releasing 2.0.0 (in our workflow we update that number as soon as we start working on it).

But, if this workflow doesn't suit your needs, you can set the mode to "verbose" like so:

```scss
$app-version: '1.1.0';
$deprecate-mode: 'verbose';

@import 'index';

@include deprecate('2.0.0', 'Use .button-new instead') {
  .button { background: red; }
}
.button-new { background: red; border: 3px solid blue; }
```

In the console you'd get these warnings:

```
WARNING: Some code will be deprecated in 2.0.0. Current version: 1.1.0.
	on line 119 of index.scss
	from line 6 of test.scss

Rendering Complete, saving .css file...
Wrote CSS to /Users/kdeloumeauprigent/workspace/sass-deprecate/test.css
```

Outputs `test.css`:
```css
.button {
  background: red; }

.button-new {
  background: red;
  border: 3px solid blue; }
```

> 3. Following up on the above and if I’m understanding correctly, in `2.0.0` you as a developer would completely _remove_ `.button` and its styles? So at this point no deprecated code would be shipped (as indicated) and therefore these deprecation warnings also do not get shipped and they would not be output to the compiler in `2.0.0`. Is this correct? Or do you continue to ship the `.button` selector wrapped in the `deprecated` mixin?

Ideally you'd remove all the blocks before shipping 2.0.0, but if you don't have time to do it or have a good reason to keep them in for some of your users, that's fine: the code for `.button` won't be in the output anyway because it's now deprecated (unless your users override `$app-version` to get old deprecated code).

sass-deprecate can adapt to many different workflows, which is why I introduced these different modes:

- `disabled`: output all the code, even if deprecated
- `silent`: disable all warnings but don't output deprecated code
- `verbose`: show all warnings, even for code that is *about* to be deprecated
- `sensible` (default): output warnings when deprecated code is detected
- `fail`: prevent compilation when deprecated code is found

See https://salesforce-ux.github.io/sass-deprecate/#undefined-variable-deprecate-mode

Hope this answers your question, I'm happy to discuss further how sass-deprecate can fit in your workflow.
